version: '3'

services:
  centrifugo:
    image: centrifugo/centrifugo
    command: centrifugo -c config.json --port=8086 --admin
    ports:
    - "8086:8086"
    volumes:
    - ./config.json:/centrifugo/config.json
